services:
  mysql:
    image: mysql:8
    container_name: payment-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql

  mysql-tests:
    image: mysql:8
    container_name: payment-mysql-tests
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment_db_test
    ports:
      - "3307:3306"
    volumes:
      - mysql_test_data:/var/lib/mysql

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    ports:
      - "3000:3333"
    volumes:
      - ./transaction-service:/app
      - /app/node_modules
    depends_on:
      - mysql
    env_file:
      - ./transaction-service/.env
    command: node ace serve --watch

volumes:
  mysql_dev_data:
  mysql_test_data:
